/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ocp.day18;

/**
 *
 * @author boddy
 */
public class LottoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LottoJFrame
     */
    public LottoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lotto_title = new javax.swing.JLabel();
        lotto_box = new javax.swing.JComboBox<>();
        lotto_button = new javax.swing.JButton();
        lotto_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("樂透電腦選號");

        lotto_title.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        lotto_title.setForeground(new java.awt.Color(102, 102, 255));
        lotto_title.setText("樂透");

        lotto_box.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        lotto_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "今彩539", "4星彩" }));

        lotto_button.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        lotto_button.setForeground(new java.awt.Color(0, 153, 0));
        lotto_button.setText("選號");
        lotto_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotto_buttonActionPerformed(evt);
            }
        });

        lotto_label.setFont(new java.awt.Font("新細明體", 0, 36)); // NOI18N
        lotto_label.setForeground(new java.awt.Color(204, 0, 0));
        lotto_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lotto_label.setText("00 00 00 00 00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lotto_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lotto_title)
                        .addGap(43, 43, 43)
                        .addComponent(lotto_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(lotto_button)))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lotto_title)
                    .addComponent(lotto_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lotto_button))
                .addGap(36, 36, 36)
                .addComponent(lotto_label, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lotto_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotto_buttonActionPerformed
        //System.out.println(lotto_box.getSelectedIndex());
        //System.out.println(lotto_box.getSelectedItem());
        int idx = lotto_box.getSelectedIndex();
        switch(idx){
            case 0:
                lotto_label.setText(LottoService.get539().toString());
                break;
            case 1:
                lotto_label.setText(LottoService.get4Stars().toString());
                break;
        }
    }//GEN-LAST:event_lotto_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LottoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LottoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LottoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LottoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LottoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> lotto_box;
    private javax.swing.JButton lotto_button;
    private javax.swing.JLabel lotto_label;
    private javax.swing.JLabel lotto_title;
    // End of variables declaration//GEN-END:variables
}
